#This query is to update a field of a table, using as filter several fields of other related tables.

UPDATE PRODUCTOSTIPOSDEINVENTARIOS,PRODUCTOS,PRODUCTOSEMPRESAS,
EMPRESAS,TIPOSDEINVENTARIOS
SET PRODUCTOSTIPOSDEINVENTARIOS.idTipoDeinventarioFK = 1
WHERE PRODUCTOS.idProducto = PRODUCTOSEMPRESAS.idProductoFK
AND EMPRESAS.idEmpresa = PRODUCTOSEMPRESAS.idEmpresaFK
AND EMPRESAS.idEmpresa = 1
AND PRODUCTOS.idProducto = PRODUCTOSTIPOSDEINVENTARIOS.idProductoFK
AND TIPOSDEINVENTARIOS.idTipoDeinventario = PRODUCTOSTIPOSDEINVENTARIOS.idTipoDeinventarioFK
